
import os
import mpc_current as mpc

#~ bv = mpc.BuildVariants()

#~ bv.AddValues('pre_release')
#~ bv.AddAliases( 'prerel', 'pre_release' )
#~ bv.AddAliases( 'some', ['release', 'debug'] )

#~ bv.SetDefault( 'some' )

#~ mpc.Build( 'Sconscript', ENV = {'PATH': os.environ['PATH']} )
mpc.Build( 'Sconscript' )
#~ mpc.SconsBuild( 'Sconscript' )

