
import os
import aql

#~ bv = mpc.BuildVariants()

#~ bv.AddValues('pre_release')
#~ bv.AddAliases( 'prerel', 'pre_release' )
#~ bv.AddAliases( 'some', ['release', 'debug'] )

#~ bv.SetDefault( 'some' )

#~ mpc.Build( 'Sconscript', ENV = {'PATH': os.environ['PATH']} )
aql.Build()
#~ mpc.SconsBuild( 'Sconscript' )

