
import aql

Import( 'env' )

files = [
              'src/main/main.cpp'
        ]

options = aql.EnvOptions( env )

options.cppdefines += ['AQL_DEBUG', 'AQL_LOG']
options.cpppath += ['src', 'src2', 'src3' ]
options.const_cpppath += 'const_hdr'
options.libpath += 'lib'

env.Program( 'test_mpc', files )


